#include <iostream>
#include <string>

using std::cin;
using std::cout;
using std::endl;
using std::string;

string J = "";
string R = "";
string F = "";
string s = "";
string Tolkien = "";
string by = "";
string TOLKIEN = "";
string Part = "";
string CONTENTS = "";
string FOREWORD = "";
string PROLOGUE = "";
string weed = "";
string Chapter = "";
string APPENDICES = "";
string Strider = "";
string INDEXES = "";
string colonists = "";
string government = "";
string Kilobytes = "";
string nephew = "";
string precious = "";
string thief = "";
string Thief = "";
string roots = "";
string Colon = "";
string Hyphen = "";
string Left_Parent = "";
string Right_Parent = "";
string Forward_Slash = "";
string Space = "";
string Period = "";
string QuestionMark = "";
string Comma = "";
string Semicolon = "";
string Apostrophe = "";
string ExclamationMark = "";
string Ah = "";
string fireworks = "";
string Yes = "";
string mind = "";
string grandmother = "";
string Exit_Variable_Text = "";
string Hear = "";
string Hurray = "";
string Hullo = "";
string Esmeralda = "";
string Well = "";
string I = "";
string ve = "";
string anyway = "";
string No = "";
string Gandalf = "";
string mountains = "";
string er = "";
string yes = "";
string Everything = "";
string It = "";
string yet = "";
string Bilbo = "";
string now = "";
string GOOD = "";
string BYE = "";
